### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, mkdir '~/Documents/GitHub/Atom-Config/images/R...

### ISSUE THREAD

**Issue by fishooo0815** [vlillies/atom-markdown-image-paste#5]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 11.6.1
**Thrown From**: [atom-markdown-image-paste](https://github.com/VernL/atom-markdown-image-paste) package 0.11.0

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, mkdir '/Users/lisa/Documents/GitHub/Atom-Config/images/README'

```
At internal/fs/utils.js:220

Error: ENOENT: no such file or directory, mkdir '/Users/lisa/Documents/GitHub/Atom-Config/images/README'
    at Object.mkdirSync (fs.js:823:3)
    at Object.paste (/packages/atom-markdown-image-paste/lib/atom-markdown-image-paste.js:45:8)
    at HTMLElement.atomMarkdownImagePastePaste (/packages/atom-markdown-image-paste/lib/atom-markdown-image-paste.js:18:53)
    at CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:352326)
    at CommandRegistry.dispatch (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:11:350801)
    at AtomEnvironment.dispatchApplicationMenuCommand (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:786918)
    at EventEmitter.t (/Applications/Atom.app/Contents/Resources/app/static/<embedded>:1:794889)
    at EventEmitter.emit (events.js:223:5)
    at Object.onMessage (electron/js2c/renderer_init.js:115:818)
```

### Commands

```
     -1:17.9.0 core:move-left (input.hidden-input)
  3x -1:17.1.0 core:move-right (input.hidden-input)
  2x -1:16.2.0 core:backspace (input.hidden-input)
  8x -1:15.5.0 core:select-right (input.hidden-input)
     -1:06.9.0 core:save (input.hidden-input)
  3x -0:36.5.0 core:backspace (input.hidden-input)
  2x -0:34.2.0 core:move-down (input.hidden-input)
     -0:32.8.0 core:move-up (input.hidden-input)
     -0:32.3.0 core:select-to-bottom (input.hidden-input)
     -0:31.9.0 core:backspace (input.hidden-input)
  2x -0:31.6.0 editor:newline (input.hidden-input)
     -0:27 core:paste (input.hidden-input)
     -0:25.7.0 editor:newline (input.hidden-input)
     -0:21.7.0 tree-view:remove (span.name.icon.icon-file-directory)
     -0:17.5.0 core:backspace (input.hidden-input)
     -0:10.7.0 atom-markdown-image-paste:paste (input.hidden-input)
```

### Non-Core Packages

```
atom-img 1.0.3 
atom-markdown-image-paste 0.11.0 
```

**Comment by fishooo0815** [comment]
I am new to GitHub. And this is my first Issue.

**Comment by fishooo0815** [comment]
Closed
